on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          cd app # Change directory to the app subfolder where package.json is located
          npm install
          npm run build --if-present

      # Add a step to compress the 'build' directory into a zip file
      - name: Compress build artifacts
        run: |
          Compress-Archive -Path app/build/* -DestinationPath app/build.zip
        if: success() # Only run this step if the build was successful

      - name: List contents of app directory
        run: |
          Get-ChildItem -Path app -Recurse
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: app/build.zip # Upload the compressed build artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          # The artifact is downloaded to the working directory,
          # so you don't need to specify a path.
          
      - name: List contents of app directory
        run: |
          Get-ChildItem -Path app -Recurse
        shell: pwsh

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FAF-CV-APP'
          slot-name: 'Production'
          package: 'build.zip' # Specify the correct path where build.zip is located
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1737B7E2BC0E4975A062CFEA0B82163A }}
